### ISSUE TITLE
Caching of WebTldRuleProvider

### ISSUE THREAD

**Issue by Nikkelmann** [tinohager/Nager.PublicSuffix#12]
According to the https://publicsuffix.org/list/ page the list should only be downloaded once a day.

> If you wish to make your app download an updated list periodically, **please use this URL and have your app download the list no more than once per day.**

To honor this you really should implement some sort of caching strategy.

**Comment by tinohager** [comment]
I have add a suggestion in the last commit. What do you think of the implementation?

**Comment by horch004** [comment]
In a webapplication where the DomainParser is frequently used, you would cache an instance of the DomainParser in a static property somewhere (since DomainParser does not provide it). But then the rules won't get updated until the webapplication get recycled and a new DomainParser is created.

Now we could create a kind of time to live for the cached DomainParser instance ourselfs. But it would be nice for the DomainParser class to provide an static instance and a cache time to live mechanisme.

Possible solution for the time to live mechanisme:
1) In the DomainParser.Get method calls a TimeToLiveCheck method on the _ruleProvider.
2) The WebTldProvider returns false when the cached file has to be refreshed.
3) When the provider returns false, the DomainParser first rebuilds the rule list.

A possible caviate might be that you would need to add a new function to the provider interface which breaks custom made providers (if there are any).

Any thoughts?

An other solution can be to add an static instance property. In the get access method you somehow do the checking. But I don't think this can be implemented well.

**Comment by tinohager** [comment]
I have add a method on WebTldRuleProvider to check is the cache is valid. What do you think?

**Comment by tinohager** [comment]
New version is available on nuget

**Comment by horch004** [comment]
Hi Tino, sorry for the late reaction.

The WebTldRuleProvider provides cache file expiration fine. But the DomainParser does not check the expiration of the provider cache and reloads the rules when necessarry.
But... we can keep a reference to the WebTldRuleProvider ourselfs and call your check method. When it returns false, we just create a new DomainParser object.
